apiVersion: apps/v1
kind: Deployment
metadata:
 name: my-tp
spec:
 selector:
  matchLabels:
   app: myapp
 replicas: 2
 template:
  metadata:
   labels:
    app: myapp
  spec:
   containers:
   - name: my-logwire
     image: houcemserver/logwire:first
