apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-devops
spec:
  selector:
    matchLabels:
      app: devops
  replicas: 6
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
      - name: devops-k8s
        image: houcemserver/devops_exemple:first
